### PR TITLE
fix(types): improve type-safety for cron callback functions

### PR DESCRIPTION
**Pull request by renejfc**
### About

This PR introduces better type safety for callback functions in the Cron implementation:

### Summary

- [x] Adds a proper `CronCallback` type definition to explicitly type the callback function parameters and return value
- [x]  Replaces generic `Function` type with the more specific `CronCallback` type
- [x]  Introduces `isCronCallback` type guard to safely check callback types at runtime
- [x]  Updates test to leverage improved typing
- [x]  Maintains backward compatibility while providing better type inference

### Checks

- [x]   all tests passing
- [x] `pre-commit` task passing
- [x]  docs for new definitions added 

---

These changes help catch potential type-related issues at compile time and provide better IDE support.

_Note: This is a type-safety improvement with no runtime behavior changes._

### CODE REVIEW

**Comment by renejfc** [comment]
My mistake—I worked directly from the master branch. Thanks for taking care of it!

Also, please feel free to change/adjust as you see fit.

**Comment by Hexagon** [comment]
LGTM

**Comment by Hexagon** [comment]
Thanks 👍

**Comment by Hexagon** [comment]
Released to npm dev channel through `9.0.1-dev.2`

**Pull request merged**
