### PR TITLE
Fix problem caused by #248 and #249

### PR DESCRIPTION
**Pull request by buzzinJohnnyBoi**
While all the tests passed in the last 2 PRs, I did not check if the jobs were actually running. If the `startAt` is in the past, it will increment to the next time, and if it is in the future, then it will add one minute for some reason.
Given the combination of these 2 factors, it caused the 1st run of an interval set in the future not to occur.
The solution to this was to just add a check that if the `startAt` and `interval` are set, then don't increment the `nextRun` by one minute because the `startAt` is already the first time it should run.

@Hexagon, I sincerely apologize that I had to send 3 PRs just to clear up one issue, but this time I have done all my testing with Uptime Kuma and all other tests I could think of and it passes everything. 

I am confidant this has fixed the issue now, I again apologize for the trouble that I caused.

### CODE REVIEW

**Comment by Hexagon** [comment]
Thanks, great fix! No worries, i have not even released it in stable branch yet. This is what we do in the dev branch 👍😀

**Comment by Hexagon** [comment]
You need to rebase this onto hexagon/dev to remove the old commits. If your unsure how to do it you can just check "Allow edits from maintainers" in this pr 👍

**Comment by buzzinJohnnyBoi** [comment]
How is this?

**Comment by Hexagon** [comment]
Looking great 💯 Will release as 8.0.3-dev.2 asap

**Pull request merged**
